name: Plugin2
version: '1.0'
main: org.example.plugin2.Plugin2
api-version: '1.21'
author: Aurelien
description: Système d'économie avec les cristaux

commands:
  bonjour:
    description: Dit bonjour au joueur
    usage: /bonjour
  coins:
    description: Gère ton solde de cristaux
    usage: /coins [pay|give|take|set|baltop|reset] [joueur] [montant]
  hub:
    description: Commandes administratives du hub (setspawn, reload).
    usage: /hub <setspawn | reload>
    permission: plugin2.admin
  uuid:
    description: Affiche l'UUID d'un joueur
    usage: /uuid <pseudo>
    permission: plugin2.admin
  plugin2:
    description: Recharge tous les caches du plugin depuis la base de données.
    usage: /plugin2 reload
    permission: plugin2.admin
  rank:
    description: Gère les ranks et leurs permissions.
    usage: /rank <create|delete|set|addperm|removeperm|list|info>
    permission: plugin2.admin


permissions:
  plugin2.admin:
    description: Donne accès aux commandes admin de l'économie (give, take, set, reset)
    default: op