name: Hub
version: '1.0'
main: fr.aurel943.hub.Hub
api-version: '1.21'
author: Aurelien
description: Plugin du serveur hub (économie en Cristaux, ranks, parkour, pets, cosmétiques)

commands:
  bonjour:
    description: Dit bonjour au joueur
    usage: /bonjour
  coins:
    description: Gère ton solde de cristaux
    usage: /coins [pay|give|take|set|baltop|reset] [joueur] [montant]
  hub:
    description: Commandes administratives du hub (setspawn, reload complet).
    usage: /hub <setspawn | reload>
  uuid:
    description: Affiche l'UUID d'un joueur
    usage: /uuid <pseudo>
    permission: hub.uuid
  rank:
    description: Gère les ranks et leurs permissions.
    usage: /rank <create|delete|set|addperm|removeperm|list|info>
    permission: hub.rank.manage
  parkour:
    description: Classement des meilleurs temps du parkour.
    usage: /parkour top


permissions:
  hub.*:
    description: Donne accès à absolument toutes les fonctionnalités admin du plugin.
    default: op
    children:
      hub.coins.view-others: true
      hub.coins.give: true
      hub.coins.take: true
      hub.coins.set: true
      hub.coins.reset: true
      hub.coins.help: true
      hub.setspawn: true
      hub.reload: true
      hub.uuid: true
      hub.rank.manage: true
      hub.parkour.build: true

  hub.coins.view-others:
    description: Voir le solde de cristaux d'un autre joueur (/coins <pseudo>)
    default: false
  hub.coins.give:
    description: Ajouter des cristaux à un joueur (/coins give)
    default: false
  hub.coins.take:
    description: Retirer des cristaux à un joueur (/coins take)
    default: false
  hub.coins.set:
    description: Définir le solde d'un joueur (/coins set)
    default: false
  hub.coins.reset:
    description: Réinitialiser l'économie entière du serveur (/coins reset)
    default: false
  hub.coins.help:
    description: Voir l'aide des commandes admin de l'économie (/coins help)
    default: false

  hub.setspawn:
    description: Définir le point de spawn du hub (/hub setspawn)
    default: false

  hub.reload:
    description: Recharger tous les caches ET hub-rules.yml depuis la base de données (/hub reload)
    default: false

  hub.uuid:
    description: Voir l'UUID d'un joueur (/uuid)
    default: false

  hub.rank.manage:
    description: Gérer les ranks et leurs permissions (/rank) — accès sensible, permet l'auto-promotion
    default: false

  hub.parkour.build:
    description: Bâtir/casser/drop/pickup dans les mondes de parkour
    default: false